<a href="https://www.kaggle.com/code/muhammedtausif/most-sixes-in-test-cricket-till-april-2022-eda?scriptVersionId=117829551" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# <div style='background-color:#ff0000;color:yellow;font-size:50px;text-align:center;padding:20px;'>Most Sixes in Test Cricket</div>
<div style='background-color:#0000ff;color:yellow;font-size:30px;text-align:center;padding:10px;'>EDA</div>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/most-sixes-in-test-cricket-till-april-2022/most-sixes-till-2022.csv

In [2]:
df = pd.read_csv('/kaggle/input/most-sixes-in-test-cricket-till-april-2022/most-sixes-till-2022.csv')

In [3]:
df

,Team,Score,4s,6s,Inns,Unnamed: 5,Result,Opposition,Ground,Match Date,Scorecard
0,New Zealand,690,66,22,2,NaN,won,v Pakistan,Sharjah,26-Nov-14,Test # 2147
1,Australia,735/6d,83,17,1,NaN,won,v Zimbabwe,Perth,9-Oct-03,Test # 1661
2,Pakistan,643,83,15,1,NaN,won,v New Zealand,Lahore,1-May-02,Test # 1600
3,India,726/9d,76,15,2,NaN,won,v Sri Lanka,Brabourne,2-Dec-09,Test # 1937
4,South Africa,543/6d,42,15,1,NaN,drawn,v West Indies,Basseterre,18-Jun-10,Test # 1961
5,New Zealand,441,46,14,1,NaN,won,v Sri Lanka,Christchurch,26-Dec-14,Test # 2151
6,England,629/6d,72,14,1,NaN,drawn,v South Africa,Cape Town,2-Jan-16,Test # 2197
7,India,323/4d,31,14,3,NaN,won,v South Africa,Visakhapatnam,2-Oct-19,Test # 2363
8,Pakistan,553,58,13,2,NaN,drawn,v Zimbabwe,Sheikhupura,17-Oct-96,Test # 1336
9,New Zealand,595,74,13,2,NaN,won,v South Africa,Auckland,18-Mar-04,Test # 1689
10,Pakistan,462,45,13,1,NaN,drawn,v England,Faisalabad,20-Nov-05,Test # 1772
11,India,502/7d,58,13,1,NaN,won,v South Africa,Visakhapatnam,2-Oct-19,Test # 2363
12,India,497/9d,57,13,1,NaN,won,v South Africa,Ranchi,19-Oct-19,Test # 2365
13,India,493/6d,56,13,2,NaN,won,v Bangladesh,Indore,14-Nov-19,Test # 2366
14,New Zealand,451,58,12,4,NaN,lost,v England,Christchurch,13-Mar-02,Test # 1594
15,Pakistan,679/7d,75,12,1,NaN,drawn,v India,Lahore,13-Jan-06,Test # 1781
16,Pakistan,765/6d,59,12,2,NaN,drawn,v Sri Lanka,Karachi,21-Feb-09,Test # 1909
17,South Africa,651,73,12,2,NaN,won,v Australia,Cape Town,19-Mar-09,Test # 1916
18,South Africa,620/4d,61,12,2,NaN,won,v India,Centurion,16-Dec-10,Test # 1985
19,Australia,570/9d,62,12,1,NaN,won,v England,Adelaide,5-Dec-13,Test # 2105
20,Bangladesh,555/6,50,12,3,NaN,drawn,v Pakistan,Khulna,28-Apr-15,Test # 2159
21,New Zealand,370,46,12,1,NaN,lost,v Australia,Christchurch,20-Feb-16,Test # 2202
22,West Indies,415/6d,40,12,3,NaN,won,v England,Bridgetown,23-Jan-19,Test # 2342
23,New Zealand,715/6d,74,12,2,NaN,won,v Bangladesh,Hamilton,28-Feb-19,Test # 2349
24,England,548/7d,34+,11,2,NaN,drawn,v New Zealand,Auckland,31-Mar-33,Test # 226
25,Australia,585,50,11,2,NaN,won,v Pakistan,Adelaide,22-Dec-72,Test # 704
26,West Indies,493,50,11,2,NaN,won,v India,Delhi,11-Dec-74,Test # 747
27,Pakistan,487/9d,30+,11,1,NaN,drawn,v India,Chennai,3-Feb-87,Test # 1066
28,New Zealand,441/5d,39,11,3,NaN,drawn,v Zimbabwe,Auckland,20-Jan-96,Test # 1323
29,Australia,652/7d,81,11,1,NaN,won,v South Africa,Johannesburg,22-Feb-02,Test # 1590
30,Pakistan,588,74,11,1,NaN,drawn,v India,Faisalabad,21-Jan-06,Test # 1782
31,West Indies,581,57,11,1,NaN,drawn,v India,Basseterre,22-Jun-06,Test # 1807
32,South Africa,584/9d,58,11,1,NaN,drawn,v Pakistan,Abu Dhabi,20-Nov-10,Test # 1979
33,Australia,550,74,11,1,NaN,drawn,v South Africa,Adelaide,22-Nov-12,Test # 2061
34,Sri Lanka,730/6d,68,11,2,NaN,won,v Bangladesh,Mirpur,27-Jan-14,Test # 2116
35,India,649/9d,64,11,1,NaN,won,v West Indies,Rajkot,4-Oct-18,Test # 2319
36,India,276/7d,25,11,3,NaN,won,v New Zealand,Wankhede,3-Dec-21,Test # 2438
37,West Indies,447/5d,52,10,3,NaN,drawn,v New Zealand,Christchurch,22-Feb-80,Test # 875
38,West Indies,246/2d,16,10,3,NaN,won,v England,St John's,11-Apr-86,Test # 1045
39,New Zealand,496/9d,44,10,2,NaN,drawn,v England,Manchester,5-Aug-99,Test # 1457
40,Pakistan,600/8d,60,10,2,NaN,won,v Sri Lanka,Galle,21-Jun-00,Test # 1501
41,South Africa,600/3d,81,10,1,NaN,won,v Zimbabwe,Harare,7-Sep-01,Test # 1562
42,West Indies,629/9d,69,10,2,NaN,drawn,v India,St John's,10-May-02,Test # 1602
43,England,407,54,10,1,NaN,won,v Australia,Birmingham,4-Aug-05,Test # 1758
44,West Indies,591,65,10,2,NaN,drawn,v Pakistan,Multan,19-Nov-06,Test # 1816
45,West Indies,522,66,10,2,NaN,won,v New Zealand,North Sound,25-Jul-12,Test # 2050
46,Australia,369/6d,42,10,3,NaN,won,v England,Perth,13-Dec-13,Test # 2107
47,New Zealand,503,61,10,1,NaN,won,v India,Auckland,6-Feb-14,Test # 2118
48,West Indies,460,48,10,2,NaN,won,v New Zealand,Port of Spain,16-Jun-14,Test # 2125
49,Pakistan,628,52,10,2,NaN,drawn,v Bangladesh,Khulna,28-Apr-15,Test # 2159
50,India,759/7d,70,10,2,NaN,won,v England,Chennai,16-Dec-16,Test # 2241

In [4]:
df.shape

(51, 11)

In [5]:
df.describe()

              6s       Inns  Unnamed: 5
count  51.000000  51.000000         0.0
mean   11.901961   1.784314         NaN
std     2.184078   0.782655         NaN
min    10.000000   1.000000         NaN
25%    10.000000   1.000000         NaN
50%    11.000000   2.000000         NaN
75%    13.000000   2.000000         NaN
max    22.000000   4.000000         NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Team        51 non-null     object
 1   Score       51 non-null     object
 2   4s          51 non-null     object
 3   6s          51 non-null     int64
 4   Inns        51 non-null     int64
 5   Unnamed: 5  0 non-null      float64
 6   Result      51 non-null     object
 7   Opposition  51 non-null     object
 8   Ground      51 non-null     object
 9   Match Date  51 non-null     object
 10  Scorecard   51 non-null     object
dtypes: float64(1), int64(2), object(8)
memory usage: 4.5+ KB

In [7]:
df.columns

Index(['Team', 'Score', '4s', '6s', 'Inns', 'Unnamed: 5', 'Result',
       'Opposition', 'Ground', 'Match Date', 'Scorecard'],
      dtype='object')

In [8]:
df.Team

0      New Zealand
1        Australia
2         Pakistan
3            India
4     South Africa
5      New Zealand
6          England
7            India
8         Pakistan
9      New Zealand
10        Pakistan
11           India
12           India
13           India
14     New Zealand
15        Pakistan
16        Pakistan
17    South Africa
18    South Africa
19       Australia
20      Bangladesh
21     New Zealand
22     West Indies
23     New Zealand
24         England
25       Australia
26     West Indies
27        Pakistan
28     New Zealand
29       Australia
30        Pakistan
31     West Indies
32    South Africa
33       Australia
34       Sri Lanka
35           India
36           India
37     West Indies
38     West Indies
39     New Zealand
40        Pakistan
41    South Africa
42     West Indies
43         England
44     West Indies
45     West Indies
46       Australia
47     New Zealand
48     West Indies
49        Pakistan
50           India
Name: Team, dtype: object

In [9]:
pd.DataFrame(df.Team.unique())

              0
0   New Zealand
1     Australia
2      Pakistan
3         India
4  South Africa
5       England
6    Bangladesh
7   West Indies
8     Sri Lanka

In [10]:
teams = df.Team.value_counts().to_frame()
teams.index.rename('Team_Name', inplace=True)
teams.rename(columns = {'Team':'Number'}, inplace = True)

In [11]:
teams

              Number
Team_Name
New Zealand        9
Pakistan           9
West Indies        9
India              8
Australia          6
South Africa       5
England            3
Bangladesh         1
Sri Lanka          1

In [12]:
teams.columns

Index(['Number'], dtype='object')

In [13]:
# plt.figure(figsize=(20,10))
# colors = sns.color_palette('bright')[0:5]
# plt.pie(teams['Number'], labels = teams['Team_name'], colors = colors, autopct='%.0f%%')
# plt.show()